config/routes.rb
Rails.application.routes.draw do
  root to: 'default#index'

  resource :sessions, only: [:new, :create, :destroy]

  get 'users', controller: :users, action: :new
  resource :user, only: [:show, :destroy]
  resources :users do
    get 'complete', to: :complete
  end

  resources :bookings, only: :index

  resources :working_days, except: :show do
    resources :bookings, only: [:create, :destroy]
  end
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  working_day_id :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :working_day

  paginates_per 10
end

app/models/session.rb
class Session
  include ActiveModel::Validations
  include ActiveModel::Conversion

  attr_accessor :name

  validates :name, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  role       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :role, presence: true

  has_many :working_days, dependent: :destroy
  has_many :bookings, dependent: :destroy

  enum role: {
    user: 0,
    fp_user: 1
  }
end

app/models/working_day.rb
# == Schema Information
#
# Table name: working_days
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  start_time :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class WorkingDay < ActiveRecord::Base
  belongs_to :user
  has_one :booking, dependent: :destroy

  validates_with RejectSameDayValidator
  validates_with RejectSundayValidator
  validates_time :start_time, between: '10:00am'...'18:00pm', if: :weekday?
  validates_time :start_time, between: '11:00am'...'15:00pm', if: :saturday?

  paginates_per 10

  private

  def weekday?
    start_time.wday != 0 && start_time.wday != 6
  end

  def saturday?
    start_time.wday == 6
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def session_check
    return @current_user if @current_user

    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to :root unless @current_user
  end

  def fp_user_only
    redirect_to :root if @current_user.try(:role) == 'user'
  end

  def user_only
    redirect_to :root if @current_user.try(:role) == 'fp_user'
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :session_check
  before_action :login_required
  before_action :user_only

  def index
    @bookings = Booking.page(params[:page]).includes(working_day: :user).where(user_id: @current_user.id).order('working_days.start_time DESC')
  end

  def create
    booking = Booking.new(user_id: @current_user.id, working_day_id: params[:working_day_id])

    if booking.save
      redirect_to root_path, flash: { success: '予約しました' }
    else
      redirect_to root_path, flash: { danger: '予約が失敗しました'}
    end
  end

  def destroy
    booking = Booking.find(params[:id]).destroy

    if booking.frozen?
      redirect_to bookings_path, flash: { success: "#{booking.working_day.start_time}を予約一覧から削除しました。" }
    else
      redirect_to bookings_path, flash: { danger: "#{booking.working_day.start_time}を予約一覧から削除出来ませんでした。" }
    end
  end
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController
  before_action :session_check

  def index
    case @current_user.try(:role)
    when 'user' then
      @working_days = WorkingDay.includes([:booking, :user]).all
    when 'fp_user' then
      @working_days = WorkingDay.includes([:booking, :user]).where(user_id: @current_user.id)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @session = Session.new
  end

  def create
    @user = User.find_by_name params_name(params)
    if @user.presence
      session[:user_id] = @user.id
        redirect_to root_path
    else
      @session = Session.new
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end

  private

  def params_name(params)
    params.require(:session).permit(:name)[:name]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :session_check

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new user_params params

    if @user.save
      redirect_to user_complete_path @user
    else
      render :new
    end
  end

  def complete
    session[:user_id] = params[:user_id]
    @user = User.find params[:user_id]
  end

  def destroy
    @current_user.destroy

    if @current_user.frozen?
      session[:user_id] = nil
      redirect_to root_path, flash: { success: "退会完了しました。" }
    else
      redirect_to user_path, flash: { danger: "退会できませんでした。" }
    end
  end

  private

  def user_params(params)
    params.require(:user).permit([:name, :role])
  end
end

app/controllers/working_days_controller.rb
class WorkingDaysController < ApplicationController
  before_action :session_check
  before_action :login_required
  before_action :fp_user_only

  def index
    @working_days = WorkingDay.page(params[:page]).where(user_id: @current_user.id).order('start_time DESC')
  end

  def new
    @working_day = WorkingDay.new
  end

  def create
    @working_day = WorkingDay.new params_working_day(params)
    @working_day.user_id = @current_user.id
    if @working_day.save
      redirect_to root_path, flash: { success: "新しく稼働日を#{@working_day.start_time}に設定しました。" }
    else
      flash.now[:danger] = "#{@working_day.start_time}は新しい稼働日に設定できませんでした。"
      render action: :new
    end
  end

  def edit
  end

  def destroy
    working_day = WorkingDay.find(params[:id]).destroy

    if working_day.frozen?
      redirect_to working_days_path, flash: { success: "#{working_day.start_time}を稼働日一覧から削除しました。" }
    else
      redirect_to working_days_path, flash: { danger: "#{working_day.start_time}を稼働日一覧から削除出来ませんでした。" }
    end
  end

  private

  def params_working_day(params)
    params.require(:working_day).permit([:start_time])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def datetime_to_ymdhm(datetime)
    datetime.strftime("%Y/%m/%d %H:%M")
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/default_helper.rb
module DefaultHelper
  def datetime_to_hm(datetime)
    "#{datetime.strftime("%H:%M")}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/working_days_helper.rb
module WorkingDaysHelper
end

app/views/bookings/index.html.haml
.panel.panel-default
  %h1
    予約日
  .row
    .col-md-12
      - if @bookings
        %ul.list-group
          - @bookings.each do |booking|
            %li.list-group-item
              = datetime_to_ymdhm(booking.working_day.start_time)
              = booking.working_day.user.name
              = link_to "削除", working_day_booking_path(booking.working_day, booking), method: :delete, class: "btn btn-danger", data: { confirm: '本当に削除しますか？' }
      - else
        予約無し
  .row
    .col-md-12
      = paginate @bookings

app/views/default/index.html.haml
.panel.panel-default
  %h1
    ダッシュボード
  - if @current_user.try(:role) == 'fp_user'
    .row
      .col-md-12
        = link_to "新しく稼働可能日を設定する", new_working_day_path, class: 'btn btn-primary'
  - if @current_user
    = week_calendar events: @working_days, number_of_weeks: 1 do |date, working_days|
      = date

      %table.table-bordered
        %tr
          %th
            時間帯
          %th
            プランナー
          %th

        - working_days.each do |working_day|
          %tr
            %td
              = datetime_to_hm working_day.start_time
            %td
              = working_day.user.name
            %td
              - if working_day.try(:booking).try(:user_id) == @current_user.id
                あなたが予約しています
              - elsif working_day.booking
                - case @current_user.role
                - when 'user'
                  予約済
                - when 'fp_user'
                  - if working_day.booking
                    = working_day.booking.user.name
                  - else
                    予約されていません
              - else
                - case @current_user.role
                - when 'user' then
                  = link_to "予約する", working_day_bookings_path(working_day), method: :post ,class: 'btn btn-primary'
                - when 'fp_user' then
                  予約されていません
  - else
    = link_to "ログイン", new_sessions_path
    もしくは
    = link_to "サインイン", new_user_path
    を行ってください。

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %a.navbar-brand{href: root_path} FP Reservation
    %ul.nav.navbar-nav.navbar-right
      - if @current_user
        %li.dropdown
          %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
            = @current_user.name
            %span.caret
          %ul.dropdown-menu
            %li
              - case @current_user.try(:role)
              - when 'user' then
                = link_to "予約一覧", bookings_path
              - when 'fp_user' then
                = link_to "稼働可能日一覧", working_days_path
            %li
              = link_to 'ユーザ設定', user_path
            %li
              = link_to 'ログアウトする', sessions_path, method: :delete
      - else
        %li.dropdown
          %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
            新規登録/ログイン
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to 'ログインする', new_sessions_path
            %li
              = link_to '新規登録する', new_user_path

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %title FpReservation
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: 'layouts/header'
    - flash.each do |key, value|
      = content_tag(:div, value, class: "alert alert-#{key}")
    .container-fluid
      .row
        .col-md-12
          = yield

app/views/users/_form.html.haml
- if user.errors.messages.size > 0
  .alert.alert-danger
    ユーザーが登録できませんでした

= form_for user, html: { class: 'form-horizontal' } do |f|
  .form-group{ class: user.errors.messages[:name] && "has-error"}
    = f.label :name, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, class: 'form-control'
      - if user.errors.messages[:name]
        .has-error
          = user.errors.messages[:name][0]
  .form-group{ class: user.errors.messages[:role] && "has-error" }
    = f.label :role, class: 'control-label col-md-2'
    .col-md-10
      = f.label :role, value: 'user', class: 'radio-inline' do
        = f.radio_button :role, 'user'
        ユーザー
      = f.label :role, value: 'fp_user', class: 'radio-inline' do
        = f.radio_button :role, 'fp_user'
        ファイナンシャルプランナー
      - if user.errors.messages[:role]
        .has-error
          = user.errors.messages[:role][0]
  .form-group
    .col-md-10.col-md-offset-2
      = f.submit "登録", class: 'btn btn-primary'

app/views/users/complete.html.haml
.row
  .col-md-6.col-md-offset-3
    .row
      .col-md-12
        = @user.name
        さん。ご登録ありがとうございます！
    .row
      .col-md-12
        = link_to "ダッシュボードへ遷移する", root_path, class: "btn btn-primary"

app/views/users/new.html.haml
.row
  .col-md-6.col-md-offset-3
    = render partial: 'users/form', locals: { user: @user }

app/views/users/show.html.haml
.row
  .col-md-6.col-md-offset-3
    %table.table
      %tr
        %th
          名前
        %td
          = @current_user.name
      %tr
        %th
          役割
        %td
          = @current_user.role
  .col-md-6.col-md-offset-3
    = link_to '退会する', user_path, method: :delete, class: 'btn btn-danger', data: { confirm: '本当に退会しますか？' }

app/views/working_days/_form.html.haml
= form_for working_day, html: { class: 'form-horizontal' } do |f|
  .form-group{ class: working_day.errors.messages[:start_time] && "has-error"}
    = f.label :start_time, class: 'control-label col-md-2'
    .col-md-10
      = f.datetime_select :start_time, use_month_numbers: true, minute_step: 30, class: 'form-control'
      - if working_day.errors.messages[:start_time]
        .has-error
          = working_day.errors.messages[:start_time][0]

  .form-group
    .col-md-10.col-md-offset-2
      = f.submit "登録", class: 'btn btn-primary'

app/views/working_days/index.html.haml
.panel.panel-default.col-md-12
  %h1
    稼働可能日
  .row
    .col-md-12
      = link_to "新しく稼働可能日を設定する", new_working_day_path, class: 'btn btn-primary'
  .row
    .col-md-12
      - if @working_days
        %ul.list-group
          - @working_days.each do |working_day|
            %li.list-group-item
              = datetime_to_ymdhm(working_day.start_time)
              = link_to "削除", working_day_path(working_day), method: :delete, class: 'btn btn-danger', data: { confirm: '本当に削除しますか？' }
      - else
        予約無し
  .row
    .col-md-12
      = paginate @working_days

app/views/working_days/new.html.haml
.panel.panel-default
  %h1
    稼働可能日作成
  .row
    .col-md-12
      = render partial: 'working_days/form', locals: {working_day: @working_day}